# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.AutoField(primary_key=True, serialize=False)),
                ('train_number', models.CharField(max_length=6)),
                ('from_city', models.CharField(max_length=128)),
                ('to_city', models.CharField(max_length=128)),
                ('ticket_price', models.IntegerField()),
                ('total_places', models.IntegerField()),
                ('free_places', models.IntegerField()),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=5)),
                ('state', models.IntegerField(default=0)),
            ],
        ),
    ]
