# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('billing_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('card', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('state', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
